CREATE TABLE BOARD(
    NUM NUMBER(4),
    PWD VARCHAR(20),
    READ_COUNT NUMBER(4) NOT NULL,
    TEXT VARCHAR(2000),
    TITLE VARCHAR(200) NOT NULL,
    WRITE_DATE DATE NOT NULL,
    WRITER VARCHAR(40) NOT NULL,
    CONSTRAINT PK_BOARD PRIMARY KEY(NUM)
);

CREATE SEQUENCE BOARD_NUM_SEQ INCREMENT BY 1 START WITH 1;
